"""
build_tools.py
==============
Utilities for compiling and testing C / C++ projects generated by EvoForge.

Responsibilities:
  - Locate the system C/C++ compiler
  - Auto-generate a Makefile
  - Compile the project (make all)
  - Compile & run C/C++ tests (make test)
"""

import os
import re
import shutil
import subprocess
from typing import List, Tuple, Optional


# ---------------------------------------------------------------------------
# Compiler detection
# ---------------------------------------------------------------------------

def find_compiler(language: str) -> Optional[str]:
    """Return the first available compiler for the given language."""
    candidates = ['g++', 'clang++', 'c++'] if language == 'cpp' else ['gcc', 'clang', 'cc']
    for cmd in candidates:
        if shutil.which(cmd):
            return cmd
    return None


def find_make() -> Optional[str]:
    """Return 'make' if it is on PATH, else None."""
    return shutil.which('make')


# ---------------------------------------------------------------------------
# Makefile generation
# ---------------------------------------------------------------------------

def _discover_sources(project_dir: str, language: str) -> List[str]:
    """Return a sorted list of relative source file paths in project_dir (recursive)."""
    exts = ('.cpp', '.cxx', '.cc') if language == 'cpp' else ('.c',)
    sources = []
    for root, dirs, files in os.walk(project_dir):
        # Skip test and hidden directories
        dirs[:] = [d for d in dirs if d not in ('tests', '.git', '__pycache__', '.venv', '.pytest_cache')]
        for fname in files:
            if fname.endswith(exts):
                sources.append(os.path.relpath(os.path.join(root, fname), project_dir))
    return sorted(sources)


def generate_makefile(project_dir: str, project_name: str, language: str) -> str:
    """Write an auto-generated Makefile into *project_dir* and return its path.

    The Makefile supports three targets:
      all   – build the main executable
      test  – build & run tests/test_runner
      clean – remove compiled artefacts
    """
    is_cpp   = (language == 'cpp')
    cc_var   = 'CXX'   if is_cpp else 'CC'
    cc_cmd   = find_compiler(language) or ('g++' if is_cpp else 'gcc')
    flag_var = 'CXXFLAGS' if is_cpp else 'CFLAGS'
    std_flag = '-std=c++17' if is_cpp else '-std=c11'
    src_ext  = 'cpp'   if is_cpp else 'c'
    # Auto-detect required linker libraries
    extra_libs = ['-lm']
    for root, _, files in os.walk(project_dir):
        for f in files:
            if f.endswith(('.c', '.cpp', '.cxx', '.cc', '.h', '.hpp', '.hxx')):
                fpath = os.path.join(root, f)
                try:
                    with open(fpath, 'r', encoding='utf-8', errors='ignore') as fh:
                        content = fh.read()
                        if ("pthread" in content or "pthread_create" in content) and "-lpthread" not in extra_libs:
                            extra_libs.append("-lpthread")
                        if ("openssl/" in content or "EVP_" in content or "SHA256" in content) and "-lssl" not in extra_libs:
                            extra_libs.extend(["-lssl", "-lcrypto"])
                except Exception:
                    pass

    libs_str = " ".join(extra_libs)

    # ── Discover source subdirectories (e.g. src/) ─────────────────────────
    sub_dirs = set()
    for entry in sorted(os.listdir(project_dir)):
        full = os.path.join(project_dir, entry)
        if os.path.isdir(full) and entry not in ('tests', '.git', '__pycache__', '.venv', '.pytest_cache'):
            # Only include dirs that actually contain source files
            if any(f.endswith('.' + src_ext) for f in os.listdir(full) if os.path.isfile(os.path.join(full, f))):
                sub_dirs.add(entry)
    sub_dirs = sorted(sub_dirs)

    # Include flags: always -I. -Itests plus -I<subdir> for each source subdir
    inc_flags = '-I. -Itests' + ''.join(f' -I{d}' for d in sub_dirs)
    full_flags = f'-Wall -Wextra {std_flag} -g {inc_flags}'

    # Build SRC/OBJ variable lines for root and each subdir
    src_lines = [f'SRC_ROOT    = $(wildcard *.{src_ext})']
    obj_lines = [f'OBJ_ROOT    = $(SRC_ROOT:.{src_ext}=.o)']
    for d in sub_dirs:
        tag = d.upper().replace('/', '_').replace('-', '_')
        src_lines.append(f'SRC_{tag}    = $(wildcard {d}/*.{src_ext})')
        obj_lines.append(f'OBJ_{tag}    = $(SRC_{tag}:.{src_ext}=.o)')

    all_obj_vars = ' '.join(
        ['$(OBJ_ROOT)'] + [f'$(OBJ_{d.upper().replace("/","_").replace("-","_")})' for d in sub_dirs]
    )
    src_block = '\n'.join(src_lines)
    obj_block = '\n'.join(obj_lines)

    # Test build excludes main.o / %main.o to avoid duplicate main symbol
    test_obj  = f'$(filter-out %main.o main.o main_%.o, {all_obj_vars})'
    link_cmd  = f'$({cc_var}) {all_obj_vars} -o $@ {libs_str}'
    test_link = f'$({cc_var}) $({flag_var}) $(TEST_SRCS) {test_obj} -o $(TEST_TARGET) {libs_str}'

    makefile = f"""\
# Auto-generated Makefile for {project_name}
# Generated by EvoForge — do not edit manually unless you know what you are doing.

{cc_var}      = {cc_cmd}
{flag_var}  = {full_flags}
TARGET      = {project_name}
{src_block}
{obj_block}
ALL_OBJ     = {all_obj_vars}
TEST_DIR    = tests
TEST_SRCS   = $(wildcard $(TEST_DIR)/*.{src_ext})
TEST_TARGET = $(TEST_DIR)/test_runner

# ── Primary build ──────────────────────────────────────────────────────────
all: $(TARGET)

$(TARGET): $(ALL_OBJ)
\t{link_cmd}

%.o: %.{src_ext}
\t$({cc_var}) $({flag_var}) -c $< -o $@

# ── Test build & run ───────────────────────────────────────────────────────
test: $(TEST_TARGET)
\t@echo "Running C/C++ tests..."
\t./$(TEST_TARGET)
\t@echo "All tests passed."

$(TEST_TARGET): $(TEST_SRCS) {test_obj}
\t@mkdir -p $(TEST_DIR)
\t{test_link}

# ── Cleanup ────────────────────────────────────────────────────────────────
clean:
\trm -f $(ALL_OBJ) $(TARGET) $(TEST_TARGET) $(TEST_DIR)/*.o

.PHONY: all test clean
"""
    path = os.path.join(project_dir, 'Makefile')
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(makefile)
    return path


# ---------------------------------------------------------------------------
# Compile & test
# ---------------------------------------------------------------------------

def compile_project(project_dir: str) -> Tuple[bool, str]:
    """Run *make all* in *project_dir*.

    Returns:
        (success: bool, combined_output: str)
    """
    if find_make() is None:
        return False, "'make' is not installed on this system."

    makefile = os.path.join(project_dir, 'Makefile')
    if not os.path.exists(makefile):
        return False, "No Makefile found — cannot compile."

    result = subprocess.run(
        ['make', 'all'],
        cwd=project_dir,
        capture_output=True,
        text=True
    )
    output = (result.stdout + '\n' + result.stderr).strip()
    return result.returncode == 0, output


def run_c_tests(project_dir: str) -> Tuple[bool, str]:
    """Run *make test* in *project_dir*.

    Returns:
        (success: bool, combined_output: str)
    """
    test_dir = os.path.join(project_dir, 'tests')
    if not os.path.isdir(test_dir):
        return True, "No tests/ directory found — skipping C/C++ tests."

    test_files = [
        f for f in os.listdir(test_dir)
        if f.endswith('.c') or f.endswith('.cpp')
    ]
    if not test_files:
        return True, "No test source files found — skipping."

    if find_make() is None:
        return False, "'make' is not installed on this system."

    result = subprocess.run(
        ['make', 'test'],
        cwd=project_dir,
        capture_output=True,
        text=True
    )
    output = (result.stdout + '\n' + result.stderr).strip()
    return result.returncode == 0, output


# ---------------------------------------------------------------------------
# Static analysis & bug detection helpers for C/C++
# ---------------------------------------------------------------------------

_INCLUDE_RE  = re.compile(r'#include\s*[<"]([\w./]+)[>"]')
_FUNC_RE     = re.compile(
    r'(?:^|\n)\s*(?:(?:static|extern|inline|const|void)\s+)*'
    r'(\w[\w\s\*]+?)\s+(\w+)\s*\(([^)]*)\)\s*\{',
    re.MULTILINE
)
_STRUCT_RE   = re.compile(r'(?:typedef\s+)?struct\s+(\w+)\s*\{', re.MULTILINE)
_MACRO_RE    = re.compile(r'#define\s+(\w+)', re.MULTILINE)

_SKIP_KEYWORDS = frozenset(['if', 'for', 'while', 'switch', 'else', 'do', 'return'])


def analyze_c_file(file_path: str, root_dir: str) -> dict:
    """Parse a C/C++ source or header file and return a summary dict."""
    try:
        with open(file_path, 'r', encoding='utf-8', errors='replace') as fh:
            code = fh.read()
    except FileNotFoundError:
        return {}

    includes = _INCLUDE_RE.findall(code)

    functions = []
    for m in _FUNC_RE.finditer(code):
        name = m.group(2).strip()
        if name in _SKIP_KEYWORDS:
            continue
        functions.append({
            'name':        name,
            'return_type': m.group(1).strip(),
            'params':      [p.strip() for p in m.group(3).split(',') if p.strip()],
        })

    structs = _STRUCT_RE.findall(code)
    macros  = _MACRO_RE.findall(code)

    return {
        'path':      os.path.relpath(file_path, root_dir),
        'language':  'cpp' if file_path.endswith(('.cpp', '.cxx', '.cc', '.hpp')) else 'c',
        'includes':  sorted(set(includes)),
        'functions': functions,
        'structs':   structs,
        'macros':    macros,
        'source':    code[:1000],
    }


def parse_c_compiler_errors(output: str) -> List[dict]:
    """Parse compiler errors from gcc/g++/clang output."""
    errors = []
    pattern = re.compile(r'^(.*?):(\d+):(?:(\d+):)?\s+(error|warning|fatal error):\s+(.*)$', re.MULTILINE)
    for match in pattern.finditer(output):
        file_path, line, col, severity, msg = match.groups()
        errors.append({
            'file': file_path.strip(),
            'line': int(line),
            'column': int(col) if col else 0,
            'severity': severity.strip(),
            'message': msg.strip()
        })
    return errors


def analyze_c_bugs(project_dir: str) -> List[dict]:
    """Perform static bug checks on C/C++ source and header files in project_dir."""
    issues = []
    for root, _, files in os.walk(project_dir):
        if any(ignored in root for ignored in [".venv", "__pycache__", ".git"]):
            continue
        for fname in files:
            if not fname.endswith(('.c', '.cpp', '.h', '.hpp', '.cxx', '.cc')):
                continue
            fpath = os.path.join(root, fname)
            rel_path = os.path.relpath(fpath, project_dir)
            try:
                with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
                    code = fh.read()
            except Exception:
                continue

            # Header guard check
            if fname.endswith(('.h', '.hpp', '.hxx')):
                if '#ifndef' not in code and '#pragma once' not in code:
                    issues.append({
                        'file': rel_path,
                        'type': 'missing_header_guard',
                        'message': f"Header file '{rel_path}' lacks include guards or #pragma once."
                    })

            # Check for malloc/free header in C
            if re.search(r'\b(malloc|realloc|calloc|free)\b', code) and not re.search(r'#include\s*[<"](stdlib\.h|cstdlib)[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"File '{rel_path}' uses memory management functions but missing <stdlib.h> / <cstdlib>."
                })

            # Check for printf/std::cout header
            if re.search(r'\bprintf\b', code) and not re.search(r'#include\s*[<"](stdio\.h|cstdio)[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"File '{rel_path}' uses printf but missing <stdio.h>."
                })
            if re.search(r'\bstd::cout\b', code) and not re.search(r'#include\s*[<"]iostream[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"File '{rel_path}' uses std::cout but missing <iostream>."
                })
            if re.search(r'\bnumeric_limits\b', code) and not re.search(r'#include\s*[<"]limits[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"File '{rel_path}' uses std::numeric_limits but missing <limits>."
                })

            # Check for bool in C
            if fname.endswith('.c') and re.search(r'\b(bool|true|false)\b', code) and not re.search(r'#include\s*[<"]stdbool\.h[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"C file '{rel_path}' uses bool/true/false but missing <stdbool.h>."
                })

            # Check for assert in C/C++
            if re.search(r'\bassert\b', code) and not re.search(r'#include\s*[<"](assert\.h|cassert)[>"]', code):
                issues.append({
                    'file': rel_path,
                    'type': 'missing_include',
                    'message': f"File '{rel_path}' uses assert but missing <assert.h> / <cassert>."
                })

    return issues


def debug_c_project(project_dir: str) -> Tuple[bool, str]:
    """Automated debugging pass for a C/C++ project in project_dir."""
    # 1. Apply static bug fixes
    bug_issues = analyze_c_bugs(project_dir)
    fix_applied = False
    for issue in bug_issues:
        fpath = os.path.join(project_dir, issue['file'])
        if not os.path.exists(fpath):
            continue
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()

        if issue['type'] == 'missing_include':
            if 'stdlib.h' in issue['message']:
                inc = "#include <stdlib.h>\n" if issue['file'].endswith('.c') else "#include <cstdlib>\n"
            elif 'stdio.h' in issue['message']:
                inc = "#include <stdio.h>\n"
            elif 'iostream' in issue['message']:
                inc = "#include <iostream>\n"
            elif 'limits' in issue['message']:
                inc = "#include <limits>\n"
            elif 'stdbool.h' in issue['message']:
                inc = "#include <stdbool.h>\n"
            elif 'assert.h' in issue['message']:
                inc = "#include <assert.h>\n" if issue['file'].endswith('.c') else "#include <cassert>\n"
            else:
                inc = ""

            if inc and inc.strip() not in content:
                content = inc + content
                with open(fpath, 'w', encoding='utf-8') as f:
                    f.write(content)
                fix_applied = True

        elif issue['type'] == 'missing_header_guard':
            guard = os.path.basename(fpath).upper().replace('.', '_').replace('-', '_')
            guard_str = f"#ifndef {guard}\n#define {guard}\n\n{content}\n\n#endif // {guard}\n"
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(guard_str)
            fix_applied = True

    # 2. Strip deprecated C++17-incompatible dynamic exception specs: throw(...)
    _THROW_SPEC_RE = re.compile(r'\s*throw\s*\([^)]*\)', re.MULTILINE)
    for root, _, files in os.walk(project_dir):
        for fname in files:
            if not fname.endswith(('.cpp', '.cxx', '.cc', '.hpp', '.hxx')):
                continue
            fpath = os.path.join(root, fname)
            try:
                with open(fpath, 'r', encoding='utf-8') as f:
                    content = f.read()
                cleaned = _THROW_SPEC_RE.sub('', content)
                if cleaned != content:
                    with open(fpath, 'w', encoding='utf-8') as f:
                        f.write(cleaned)
                    fix_applied = True
            except Exception:
                pass

    # 3. Regenerate Makefile to pick up any newly added subdirectories
    lang = 'cpp'
    for root, _, files in os.walk(project_dir):
        if any(f.endswith('.c') and not f.endswith(('.cpp', '.cxx', '.cc')) for f in files):
            lang = 'c'
            break
    project_name = os.path.basename(project_dir)
    generate_makefile(project_dir, project_name, lang)

    # 4. Try compilation
    comp_ok, comp_out = compile_project(project_dir)
    if not comp_ok:
        parsed_errs = parse_c_compiler_errors(comp_out)
        return False, f"Compilation failed with {len(parsed_errs)} errors:\n{comp_out}"

    # 5. Try tests
    test_ok, test_out = run_c_tests(project_dir)
    if not test_ok:
        return False, f"C/C++ tests failed:\n{test_out}"

    return True, "All C/C++ files compiled and passed unit tests successfully."

